version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           mkdir test
           cd test
           echo "$(pwd)"
           echo "$HOME"
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
