version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
          print $pwd
          print $HOME
          printenv
          ls
          
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
