version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           printenv
           print $pwd
           print$HOME
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
